quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=Password09
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:54325/postgres?currentSchema=resource_owner_password_1_schema

quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true

# sign with  RSA private key
quarkus.smallrye-jwt.sign.key-location=privateKey.pem

# verify incoming tokens against  public key
mp.jwt.verify.publickey.location=publicKey.pem

# allow bearer-only endpoints
quarkus.http.auth.permission.authenticated.paths=/api/*
quarkus.http.auth.permission.authenticated.policy=authenticated

# (optional) disable form-based login
quarkus.http.auth.form.enabled=false


